apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zeppelin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zeppelin
    spec:
      containers:
        - name: zeppelin
          imagePullPolicy: IfNotPresent
          image: immortalhuang/zhiweicloud-zeppelin
          command: ["/opt/zeppelin/bin/zeppelin.sh","--config","/opt/zeppelin/conf"]
---
apiVersion: v1
kind: Service
metadata:
  name: zeppelin-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: zeppelin